### ISSUE TITLE
Throws a error when try to reconnect

### ISSUE THREAD

**Issue by dima12qw** [VladimirMikhailov/elixir_simple_tcp#3]
Can you explain me how to recconect to another channel? Because it throws an error, or maybe it's something that I'm doing wrong..

**Comment by VladimirMikhailov** [comment]
@dima12qw Hey, the app hasn't been updating for a while and seems there was an issues in `GenServer` termination. I have pushed a fix to the master. Please take a look and let me know if it works fine. 

Thanks

**Comment by dima12qw** [comment]
It works now. Thank you
